### ISSUE TITLE
Ability to filter and view volunteer wise , coach wise, fellow / city wise data at NFH level. Coach wise and Volunteer wise data at fellow level and volunteer wise data at coach level. 

### ISSUE THREAD

**Issue by adityasurneni** [godreams/admin-server#29] opened 2017-02-22 05:54 UTC
It would lead to massive confusion attributing donations to the respective people :/

**Comment by harigopal** [comment] 2017-03-05 17:00
Noting that this appears to be a dupe of the following:

* https://github.com/godreams/admin-server/issues/16
* https://github.com/godreams/admin-server/issues/17
* https://github.com/godreams/admin-server/issues/12

**Comment by ajaleelp** [comment] 2017-03-29 18:59
This has been completed. For final code refer:
https://github.com/godreams/admin-server/blob/master/app/services/donations/filter_service.rb
https://github.com/godreams/admin-server/blob/master/app/forms/donations/filter_form.rb
https://github.com/godreams/admin-server/blob/master/app/views/donations/index.html.erb#L23-L41
https://github.com/godreams/admin-server/blob/master/app/controllers/donations_controller.rb#L6-L10

**Closed by ajaleelp** 2017-03-29 18:59 UTC
Labels: enhancement
